'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wc_order_reconsile

    '''<summary>
    '''Label17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chk_reconsile_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_11 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_16 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_12 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_17 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_8 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_13 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_18 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_9 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_14 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_19 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_10 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_15 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_reconsile_20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_reconsile_20 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btn_reconsile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_reconsile As Global.System.Web.UI.WebControls.Button
End Class
