Public Class skl_inventory
	Inherits iFoundation.cls_skelet

	Public _id As Int32
	Public _platetype As Int32
	Public _category_id As Int32
	Public _subcategory_id As Int32
	Public _location_id As Int32
	Public _branchnumber As Int32
	Public _suppliernumber As Int32
	Public _itemnumberint As Int32
	Public _itemnumber As String
	Public _itemcode As String
	Public _active As Boolean
	Public _deleted As Boolean
	Public _no_orderalone As Boolean
    Public _no_publicauction As Boolean
	Public _status_id As Int32
	Public _lang1_description As String
	Public _lang2_description As String
	Public _lang3_description As String
	Public _lang4_description As String
	Public _lang5_description As String
	Public _lang6_description As String
	Public _createdate As DateTime
	Public _onprocess As Boolean
	Public _onauction As Boolean
	Public _onspecial As Boolean
	Public _onspecial_from_date As DateTime
	Public _onspecial_to_date As DateTime
	Public _qtyonstock_cur As Int16
	Public _qtyonstock_min As Int16
    Public _purchase_price As Decimal
	Public _appraisal_price As Decimal
	Public _dealer_price As Decimal
	Public _sell_price As Decimal
	Public _special_sell_price As Decimal
	Public _special_dealer_price As Decimal
	Public _notes As String
	Public _icon_pic As String
	Public _picture_pic As String
	Public _picture_hires_pic As String
	Public _certificate_pic As String
	Public _movie_pic As String
	Public _gallery_pic As String
	Public _banner_pic As String
	Public _similar_items As String
	Public _lastmodify_user As String
	Public _lastmodify_user_id As Int32
	Public _lastmodify_date As DateTime
	Public _indexwords As String
	Public _remarks As String
	Public _club_item As Boolean
	Public _autogenerated As Boolean
	Public _item_sold As Boolean
    Public _subplate As Object
    Public _middlestone As String
    Public _smartsort_txt As String
    Public auction_price As Decimal
    Public release_date As DateTime
    Public onbargain As Boolean
    Public samplepic As Boolean
    Public featured As Boolean
    Public itemsold As Boolean = False
    Public opthash As New Hashtable
    Public has_white_gold As Boolean
    Public has_yellow_gold As Boolean
    Public has_movie As Boolean


    Sub New()
        Me._id = 0
        Me._platetype = 0
        Me._category_id = 0
        Me._subcategory_id = 0
        Me._location_id = 0
        Me._branchnumber = 0
        Me._suppliernumber = 0
        Me._itemnumberint = 0
        Me._itemnumber = ""
        Me._itemcode = ""
        Me._active = False
        Me._deleted = False
        Me._no_orderalone = False
        Me._no_publicauction = False
        Me._status_id = 0
        Me._lang1_description = ""
        Me._lang2_description = ""
        Me._lang3_description = ""
        Me._lang4_description = ""
        Me._lang5_description = ""
        Me._lang6_description = ""
        Me._createdate = #1/1/1900#
        Me._onprocess = False
        Me._onauction = False
        Me._onspecial = False
        Me._onspecial_from_date = #1/1/1900#
        Me._onspecial_to_date = #1/1/1900#
        Me._qtyonstock_cur = 0
        Me._qtyonstock_min = 0
        Me._purchase_price = 0
        Me._appraisal_price = 0
        Me._dealer_price = 0
        Me._sell_price = 0
        Me._special_sell_price = 0
        Me._special_dealer_price = 0
        Me._notes = ""
        Me._icon_pic = ""
        Me._picture_pic = ""
        Me._picture_hires_pic = ""
        Me._certificate_pic = ""
        Me._movie_pic = ""
        Me._gallery_pic = ""
        Me._banner_pic = ""
        Me._similar_items = ""
        Me._lastmodify_user = ""
        Me._lastmodify_user_id = 0
        Me._lastmodify_date = #1/1/1900#
        Me._indexwords = ""
        Me._remarks = ""
        Me._club_item = False
        Me._autogenerated = False
        Me._item_sold = False
        Me._subplate = Nothing
        Me._middlestone = ""
        Me._smartsort_txt = ""
        Me.onbargain = False
        Me.samplepic = False
        Me.featured = False
    End Sub

End Class
